# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [2]:
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', sep = '|', index_col= 'user_id')
users.head()

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

### Step 4. Discover what is the mean age per occupation

In [3]:
users.groupby('occupation').age.mean()

occupation
administrator    38.746835
artist           31.392857
doctor           43.571429
educator         42.010526
engineer         36.388060
entertainment    29.222222
executive        38.718750
healthcare       41.562500
homemaker        32.571429
lawyer           36.750000
librarian        40.000000
marketing        37.615385
none             26.555556
other            34.523810
programmer       33.121212
retired          63.071429
salesman         35.666667
scientist        35.548387
student          22.081633
technician       33.148148
writer           36.311111
Name: age, dtype: float64

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [4]:
users['numeric_gender'] = users['gender'].apply(lambda x : 1 if x =='M' else 0)
df = users.groupby('occupation').numeric_gender.sum() / users.occupation.value_counts() * 100
df.sort_values(ascending= False)

occupation
doctor           100.000000
engineer          97.014925
technician        96.296296
retired           92.857143
programmer        90.909091
executive         90.625000
scientist         90.322581
entertainment     88.888889
lawyer            83.333333
salesman          75.000000
educator          72.631579
student           69.387755
other             65.714286
marketing         61.538462
writer            57.777778
none              55.555556
administrator     54.430380
artist            53.571429
librarian         43.137255
healthcare        31.250000
homemaker         14.285714
dtype: float64

### Step 6. For each occupation, calculate the minimum and maximum ages

In [5]:
# users.groupby('occupation').agg(
#     min_age = ('age', 'min'),
#     max_age = ('age', 'max')
# )

users.groupby('occupation').age.agg(['min', 'max'])

               min  max
occupation
administrator   21   70
artist          19   48
doctor          28   64
educator        23   63
engineer        22   70
entertainment   15   50
executive       22   69
healthcare      22   62
homemaker       20   50
lawyer          21   53
librarian       23   69
marketing       24   55
none            11   55
other           13   64
programmer      20   63
retired         51   73
salesman        18   66
scientist       23   55
student          7   42
technician      21   55
writer          18   60

### Step 7. For each combination of occupation and gender, calculate the mean age

In [6]:
users.groupby(['occupation', 'gender']).age.mean().reset_index()

       occupation gender        age
0   administrator      F  40.638889
1   administrator      M  37.162791
2          artist      F  30.307692
3          artist      M  32.333333
4          doctor      M  43.571429
5        educator      F  39.115385
6        educator      M  43.101449
7        engineer      F  29.500000
8        engineer      M  36.600000
9   entertainment      F  31.000000
10  entertainment      M  29.000000
11      executive      F  44.000000
12      executive      M  38.172414
13     healthcare      F  39.818182
14     healthcare      M  45.400000
15      homemaker      F  34.166667
16      homemaker      M  23.000000
17         lawyer      F  39.500000
18         lawyer      M  36.200000
19      librarian      F  40.000000
20      librarian      M  40.000000
21      marketing      F  37.200000
22      marketing      M  37.875000
23           none      F  36.500000
24           none      M  18.600000
25          other      F  35.472222
26          other      M  34.028986
27     programmer      F  32.166667
28     programmer      M  33.216667
29        retired      F  70.000000
30        retired      M  62.538462
31       salesman      F  27.000000
32       salesman      M  38.555556
33      scientist      F  28.333333
34      scientist      M  36.321429
35        student      F  20.750000
36        student      M  22.669118
37     technician      F  38.000000
38     technician      M  32.961538
39         writer      F  37.631579
40         writer      M  35.346154

### Step 8.  For each occupation present the percentage of women and men

In [7]:
df = users.groupby('occupation').numeric_gender.sum() / users.occupation.value_counts() * 100
df = df.reset_index().rename(columns= {0 : 'male_percentage'})
df['female_percentage'] = 100 - df['male_percentage']
df

       occupation  male_percentage  female_percentage
0   administrator        54.430380          45.569620
1          artist        53.571429          46.428571
2          doctor       100.000000           0.000000
3        educator        72.631579          27.368421
4        engineer        97.014925           2.985075
5   entertainment        88.888889          11.111111
6       executive        90.625000           9.375000
7      healthcare        31.250000          68.750000
8       homemaker        14.285714          85.714286
9          lawyer        83.333333          16.666667
10      librarian        43.137255          56.862745
11      marketing        61.538462          38.461538
12           none        55.555556          44.444444
13          other        65.714286          34.285714
14     programmer        90.909091           9.090909
15        retired        92.857143           7.142857
16       salesman        75.000000          25.000000
17      scientist        90.322581           9.677419
18        student        69.387755          30.612245
19     technician        96.296296           3.703704
20         writer        57.777778          42.222222

In [21]:
gender_occu = users.groupby(['occupation', 'gender']).gender.agg('count')
# gender_occu
occupation_count = users.occupation.value_counts(sort = False)
# occupation_count
percentage_gender_occu = gender_occu.div(occupation_count, level = 'occupation') * 100
percentage_gender_occu.reset_index()

       occupation gender           0
0   administrator      F   45.569620
1   administrator      M   54.430380
2          artist      F   46.428571
3          artist      M   53.571429
4          doctor      M  100.000000
5        educator      F   27.368421
6        educator      M   72.631579
7        engineer      F    2.985075
8        engineer      M   97.014925
9   entertainment      F   11.111111
10  entertainment      M   88.888889
11      executive      F    9.375000
12      executive      M   90.625000
13     healthcare      F   68.750000
14     healthcare      M   31.250000
15      homemaker      F   85.714286
16      homemaker      M   14.285714
17         lawyer      F   16.666667
18         lawyer      M   83.333333
19      librarian      F   56.862745
20      librarian      M   43.137255
21      marketing      F   38.461538
22      marketing      M   61.538462
23           none      F   44.444444
24           none      M   55.555556
25          other      F   34.285714
26          other      M   65.714286
27     programmer      F    9.090909
28     programmer      M   90.909091
29        retired      F    7.142857
30        retired      M   92.857143
31       salesman      F   25.000000
32       salesman      M   75.000000
33      scientist      F    9.677419
34      scientist      M   90.322581
35        student      F   30.612245
36        student      M   69.387755
37     technician      F    3.703704
38     technician      M   96.296296
39         writer      F   42.222222
40         writer      M   57.777778

<!-- gender_count = users.groupby(['occupation', ]) -->