# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [22]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [23]:
s1 = pd.Series(np.random.randint(low = 1, high = 5, size = 100, dtype = 'l'))
s2 = pd.Series(np.random.randint(low = 1, high = 3, size = 100, dtype = 'l'))
s3 = pd.Series(np.random.randint(low = 10000, high = 30001, size = 100, dtype = 'l'))

s1, s2, s3

(0     4
 1     2
 2     1
 3     1
 4     2
      ..
 95    4
 96    2
 97    4
 98    3
 99    1
 Length: 100, dtype: int64,
 0     2
 1     1
 2     1
 3     1
 4     2
      ..
 95    1
 96    2
 97    2
 98    2
 99    2
 Length: 100, dtype: int64,
 0     16330
 1     26313
 2     10197
 3     10247
 4     27726
       ...
 95    20032
 96    20173
 97    17342
 98    20407
 99    11082
 Length: 100, dtype: int64)

### Step 3. Let's create a DataFrame by joinning the Series by column

In [24]:
# df = pd.DataFrame({0 : s1, 1 : s2, 2 : s3})
housemkt = pd.concat([s1, s2, s2], axis = 1)
housemkt

    0  1  2
0   4  2  2
1   2  1  1
2   1  1  1
3   1  1  1
4   2  2  2
.. .. .. ..
95  4  1  1
96  2  2  2
97  4  2  2
98  3  2  2
99  1  2  2

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [25]:
housemkt.rename(columns = {
    0 : 'bedrs',
    1 : 'bathrs',
    2 : 'price_sqr_meter'
    },
    inplace= True
)
housemkt

    bedrs  bathrs  price_sqr_meter
0       4       2                2
1       2       1                1
2       1       1                1
3       1       1                1
4       2       2                2
..    ...     ...              ...
95      4       1                1
96      2       2                2
97      4       2                2
98      3       2                2
99      1       2                2

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [26]:
bigcolumn = pd.concat((s1, s2, s3))
# type(bigcolumn)
bigcolumn = bigcolumn.to_frame()
print(type(bigcolumn))
bigcolumn

<class 'pandas.DataFrame'>

        0
0       4
1       2
2       1
3       1
4       2
..    ...
95  20032
96  20173
97  17342
98  20407
99  11082

[300 rows x 1 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [27]:
print(bigcolumn.shape)
len(bigcolumn)

(300, 1)

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [28]:
bigcolumn.reset_index(drop= True, inplace = True)
bigcolumn

         0
0        4
1        2
2        1
3        1
4        2
..     ...
295  20032
296  20173
297  17342
298  20407
299  11082

[300 rows x 1 columns]